### ISSUE TITLE
Refresh Tokens

### ISSUE THREAD

**Issue by stephenbawks** [pulumi/pulumi-auth0#101]
## Issue details

I do not see the ability to pass in refresh tokens when creating a `connection` and wondering if that is under some other resource or if that is still needing to be added?  Under the `options` there are three values that I can specify when using the auth0cli.

admin_access_token: `somevaluehere`
admin_access_token_expiresin: `somevaluehere`
admin_refresh_token: `somevaluehere`

### Affected area/feature

Pulumi or Terraform

**Comment by leezen** [comment]
Wouldn't these values be ephemeral and not something you'd configure as part of your infrastructure? Could you please describe a bit more about your use case?

**Comment by stephenbawks** [comment]
As part of our CICD and using the auth0cli if you don't persist the refresh token information on an update/deploy it will not save those and hence for you to accept the connection again.  Super annoying. 

So I persist those and reinfect them when we do deploys. Be nice if the Pulumi provider would support those attributes.

**Comment by iwahbe** [comment]
The `auth0` provider now accepts a `apiToken` argument, though to avoid https://github.com/pulumi/pulumi/issues/4981 I would pass `apiToken` via an environmental variable.

@stephenbawks, if this wasn't what you meant please open a new issue with a code example of what you would like to work.
