### ISSUE TITLE
Auth0 Promts Functionality

### ISSUE THREAD

**Issue by ThatOneAwkwardGuy** [pulumi/pulumi-auth0#106]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

### Steps to reproduce

1. Try and create a prompt using the Auth0 Pulumi library

Expected: To be able to create a Prompt
Actual: Missing the ability to set the prompt, language, and body required by the API [here](https://auth0.com/docs/api/management/v2#!/Prompts/put_custom_text_by_language)

**Comment by ThatOneAwkwardGuy** [comment]
should be fixed with https://github.com/pulumi/pulumi-auth0/issues/107

**Comment by stack72** [comment]
Closed via #107
