### ISSUE TITLE
Toggle connections via client api

### ISSUE THREAD

**Issue by duvet86** [pulumi/pulumi-auth0#116]
Hello, I am using the [client class](https://www.pulumi.com/registry/packages/auth0/api-docs/client/) to create an auth0 SPA.
I cannot find a way to enable/disable specific connections.
Is it currently possible?
If not it would be a nice feature to have.

Thanks.

**Comment by viveklak** [comment]
I believe you can create [connections](https://www.pulumi.com/registry/packages/auth0/api-docs/connection/#enabledclients_nodejs) and add/remove clients from the `enabledClients` list.
