### ISSUE TITLE
Auth0 Attack Protection Support

### ISSUE THREAD

**Issue by ryan-neal-gds** [pulumi/pulumi-auth0#129]
## Hello!
Requesting to add support to configure Attack Protection, see [here](https://auth0.com/docs/secure/attack-protection)

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The Auth0 Pulumi package does not currently support the ability to configure Attack Protection, which is a security feature of Auth0. The Auth0 Management API V2 provides this support.

The ability to automate attack protection on Auth0 would streamline SRE activities. 

### Affected area/feature

N/A

**Comment by guineveresaenger** [comment]
Hi @ryan-neal-gds - thank you for filing this!

We will incorporate this into the next release and have this available for you.
