### ISSUE TITLE
Upgrading from 2.8.0 to > 2.10.0 causes mismatched type issue

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi-auth0#156]
### What happened?

When we upgrade from 2.8.0 to the latest version, it throws the following error: 
```
error: unmarshaling urn:...$auth0:index/tenant:Tenant$auth0:index/connection:Connection::connection-dev's instance state: could not read field options: '' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[]'
```
This is because of a breaking change in https://github.com/auth0/terraform-provider-auth0/releases/tag/v0.32.0

- resource/auth0_connection: Changed options.fields_map from Map to String (https://github.com/auth0/terraform-provider-auth0/pull/207)
- Please make sure to do a terraform state rm auth0_connection.<resource name> && terraform import auth0_connection.<resource name> <connID> in order to prevent issues due to the breaking change after upgrading to this version.

### Steps to reproduce

Start with 2.8.0 in your pulumi program and then upgrade. Run a pulumi up. 

### Expected Behavior

It should pulumi up without error. 

### Actual Behavior

The error mentioned above. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rshade** [comment]
Steps to fix:

1. pulumi state delete $urn
2. pulumi import auth0:index/connection:Connection

**Comment by guineveresaenger** [comment]
I updated the [relase notes for 2.10.0](https://github.com/pulumi/pulumi-auth0/releases/tag/v2.10.0). This is within expectation for a minor version upgrade.
