### ISSUE TITLE
upgrade auth0 v2.12.0 from v2.4.0 appears to have a problem with apiToken config

### ISSUE THREAD

**Issue by javier-fiore** [pulumi/pulumi-auth0#158]
### What happened?

Once upgrade version of auth0 plugin to v2.12.0, same code that was working with v2.4.0 appears to have a problem.
The error that I receive is:
```
   error: Preview failed: could not validate provider configuration: 3 errors occurred:
        * Conflicting configuration arguments: "client_id": conflicts with api_token
        * Conflicting configuration arguments: "client_secret": conflicts with api_token
        * Conflicting configuration arguments: "api_token": conflicts with client_id
```

My provider configuration doesn't use apiToken, so this value is not set in my configuration.

### Steps to reproduce

Just upgrade v2.12.0 of the auth0 plugin, try to instance the provider with this provider configuration:
export const providerArguments = {
  domain: providerConfig.require('domain'),
  clientId: providerConfig.require('clientId'),
  clientSecret: providerConfig.requireSecret('clientSecret'),
};

### Expected Behavior

Configure the provider without apitoken, using client and secret configuration.

### Actual Behavior

```
   error: Preview failed: could not validate provider configuration: 3 errors occurred:
        * Conflicting configuration arguments: "client_id": conflicts with api_token
        * Conflicting configuration arguments: "client_secret": conflicts with api_token
        * Conflicting configuration arguments: "api_token": conflicts with client_id
```

### Versions used

v2.12.0, but it is happening from version v2.8.0 when they add ApiToken on the constructor for the provider.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by javier-fiore** [comment]
I stay on v2.6.0 and it works ok for me. Please check what happen once this file was change on 2.7.0 and how the configuration it is parsed:

v2.6.0: https://github.com/pulumi/pulumi-auth0/blob/v2.6.0/sdk/nodejs/provider.ts

and v2.7.0 here: https://github.com/pulumi/pulumi-auth0/blob/v2.7.0/sdk/nodejs/provider.ts

with this change, my code doesn't work anymore.

**Comment by stack72** [comment]
This is related to https://github.com/pulumi/pulumi-terraform-bridge/issues/577

**Comment by VenelinMartinov** [comment]
I just tested the following program with pulumi-auth0 2.24.3 and the issue no longer reproduces.

```python
import pulumi
import pulumi_auth0 as auth0

auth0.Provider(
    "auth0",
    client_id="AVe2EyyVWiFTd5u2gI9n7LvDjxyVuVeh",
    client_secret="Z-EQPy-aqGL6ivXAcyiF1gZkFXT5Bc--R2ybNU3aTz587KjgZ787xMvOQaW8_nmz",
    domain="dev-lsmze09x.auth0.com",
)
```
