### ISSUE TITLE
Delete CustomDomain 

### ISSUE THREAD

**Issue by SharonVaughan** [pulumi/pulumi-auth0#207]
Hello

I am playing around with running two Auth0 CustomDomains. After having created two, I don't seem to be able to unprotect, then delete both of them.

I need some help deleting them from our develop tenant.

Thanks

**Comment by aureq** [comment]
The error message you're getting indicates Pulumi is trying to create a `CustomDomain` that already exists in your account when you run `pulumui up`. If your stack doesn't contain important resources, simply try running `pulumi destroy`.

Also, could you please ping me on our community Slack? I may be easier to look into your issue rather that using a github issue.

Thanks.

**Comment by SharonVaughan** [comment]
Oh sure. Thanks for your help

**Comment by SharonVaughan** [comment]
Have moved away from this issue format as this isn't the best way to communicate about our problem
