### ISSUE TITLE
Github connection scopes ignored

### ISSUE THREAD

**Issue by jasonkuhrt** [pulumi/pulumi-auth0#215]
### What happened?

Setting scopes has no effect other than cleaning out any set scopes (e.g. via UI).

### Expected Behavior

I can set scopes.

### Steps to reproduce

```
new Auth0.Connection(`github`, {
  options: {
    clientId: `...`,
    clientSecret: `...`,
    scopes: [`read:user`, `user:email`],
  },
  strategy: `github`,
})
```
Take something like above. Apply it. See the the scopes are not applied on the created resource (check the UI or call the api).

### Output of `pulumi about`

```
CLI          
Version      3.62.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.2.1
Arch     arm64

This project is written in nodejs: executable='/Users/jasonkuhrt/Library/pnpm/node' version='v16.19.0'

Current Stack: prisma-pdp/control-plane/preview

TYPE                               URN
pulumi:pulumi:Stack                urn:pulumi:preview::control-plane::pulumi:pulumi:Stack::control-plane-preview
pulumi:providers:auth0             urn:pulumi:preview::control-plane::pulumi:providers:auth0::default_2_18_0
auth0:index/client:Client          urn:pulumi:preview::control-plane::auth0:index/client:Client::control-plane
auth0:index/connection:Connection  urn:pulumi:preview::control-plane::auth0:index/connection:Connection::github


Found no pending operations associated with prisma-pdp/preview

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jasonkuhrt
User           jasonkuhrt
Organizations  jasonkuhrt, prisma-pdp

Pulumi locates its logs in /var/folders/kj/42l7g3mx7nn5yvygg5w9t7hh0000gn/T/ by default
warning: Failed to get information about the Pulumi program's dependencies: could not find either /Users/jasonkuhrt/projects/prisma/pdp-spike-control-plane-v2/infra/yarn.lock or /Users/jasonkuhrt/projects/prisma/pdp-spike-control-plane-v2/infra/package-lock.json
```

**Comment by jazzyfresh** [comment]
Thank you for reporting this! This has been added to our project board

**Comment by jasonkuhrt** [comment]
@jazzyfresh Thanks. fwiw this is a blocker issue for us. We will re-consider using Pulumi once this issue is fixed.

**Comment by mjeffryes** [comment]
Unfortunately, it looks like this issue hasn't seen any updates in a while. If you're still encountering this problem, could you leave a quick comment to let us know so we can prioritize it? (Commenting will bump it back into our triage queue.)

**Comment by jasonkuhrt** [comment]
Hey, I'm no longer on this project nor is the project using Auth0 nor am I at Prisma anymore. So I unfortunately won't be back here to offer any more context.

**Comment by guineveresaenger** [comment]
Since this issue isover a year old, we will close it for now. Anyone running into similar concerns, please re-open or file a new issue.
