### ISSUE TITLE
Action Runtime For 'node18-actions' Unavailable

### ISSUE THREAD

**Issue by source-studio** [pulumi/pulumi-auth0#274]
### What happened?

I'm trying to define an Action with a [`runtime`](https://www.pulumi.com/registry/packages/auth0/api-docs/action/#runtime_csharp) of `node-18-actions`, which is the generally available Node 18 runtime version, but the Pulumi provider does not appear to accept it:

```
error: auth0:index/action:Action resource '<redacted>' has a problem: expected runtime to be one of [node12 node16 node18], got node18-actions. Examine values at '<redacted>'.
```

### Expected Behavior

I expect the `node-18-actions` value to be valid, since this is the default value used by the UI.

### Steps to reproduce

Define an Action with a `runtime` version of `node-18-actions` and attempt to deploy it.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Hello @source-studio,

Thank you for bringing up this issue.

Upon investigation, it seems that the feature you've mentioned has recently been added to the upstream Terraform provider that Pulumi Auth0 utilizes. This update is targeted to be included in the next major release of the [upstream provider](https://github.com/auth0/terraform-provider-auth0/releases/tag/v1.0.0-beta.0). Once this major release becomes stable and is officially launched, we will proceed to update our fork to incorporate these new changes. This update will enable the GA (general availability) version of the node-18 runtime to be supported.

We appreciate your patience while we work on implementing these improvements. If you have any further questions or concerns, feel free to let us know. Your contributions and feedback are highly valued as we strive to enhance our services.

**Comment by source-studio** [comment]
The `node18-actions` runtime appears to be available in the latest version of the provider now 👍
