### ISSUE TITLE
"Use ID instead of Email for Auth0 User ID" missing on Google Workspace connections (google-apps)

### ISSUE THREAD

**Issue by shalabi** [pulumi/pulumi-auth0#283]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

### Affected area/feature

Currently there is no way to set "map_user_id_to_id" for Google Workspace connections

![image](https://github.com/pulumi/pulumi-auth0/assets/171654/4373280f-c5a6-4ded-9ef4-d16e617dec52)

Please have been working around this in terraform, by adding 
`
map_user_id_to_id": true
`
see:
https://community.auth0.com/t/how-to-enable-use-id-instead-of-email-for-auth0-user-id-using-terraform/107997/3

**Comment by shalabi** [comment]
Thanks… it still does not seem to be in terraform just yet as a first class property. Folks are adding it by convention. The suggestion you made do not work. Is there a way to send a property all the way through terraform?

**Comment by danielrbradley** [comment]
You can use [the transformation resource option](https://www.pulumi.com/docs/concepts/options/transformations/) to modify the state of the resource and add arbitary properties, but I'm not entirely sure if this will be persisted through the provider or dropped at another layer. Worth an experiment perhaps?

**Comment by shalabi** [comment]
Seems terraform just added support for this:
https://github.com/auth0/terraform-provider-auth0/pull/840

**Comment by shalabi** [comment]
> You can use [the transformation resource option](https://www.pulumi.com/docs/concepts/options/transformations/) to modify the state of the resource and add arbitary properties, but I'm not entirely sure if this will be persisted through the provider or dropped at another layer. Worth an experiment perhaps?

That did not work :(

**Comment by iwahbe** [comment]
It looks like this is fixed in pulumi-auth0. On `auth0.Connection.options` there is a `mapUserIdToId` field:

```yaml
name: dev-yaml
runtime: yaml
resources:
  connection:
    type: auth0:Connection
    properties:
      strategy: google-workspace
      options:
        mapUserIdToId: true
```

I can point you to how to find it if you let me know what language you're working in.
