### ISSUE TITLE
refresh token support

### ISSUE THREAD

**Issue by owenhaynes** [pulumi/pulumi-auth0#30]
There is currently no way set the Application Refresh Token Behavior

**Comment by leezen** [comment]
Thanks for the request. This would need to be implemented upstream.

**Comment by owenhaynes** [comment]
By implmented upstream you mean? https://github.com/alexkappa/terraform-provider-auth0/releases as this was added in v0.13.0

**Comment by leezen** [comment]
Thanks for pointing that out. In that case, it should get picked up the next time we update this provider, which should be in the next few days.

**Comment by tiagob** [comment]
I need this too. "rotating" refresh tokens are recommended for native apps

**Comment by tiagob** [comment]
@leezen could you provide an update on when a new version will be published?

This would be really helpful for the full-stack generator I'm working on which uses Pulumi to manage infra, [create full stack](https://github.com/tiagob/create-full-stack). This tool will make it easier for developers to use Pulumi
