### ISSUE TITLE
 v2.24.3 New style auth0.RolePermissions does not work

### ISSUE THREAD

**Issue by 1tmb** [pulumi/pulumi-auth0#308]
### What happened?

1. Can't attach permissions to a role (pulumi preview successful, pulumi up fails with `expected non-nil error with nil state during Create of ...  :auth0:index/rolePermissions:RolePermissions:`
2. Failure undeploys unrelated resources without updating the state file

```
  "dependencies": {
   "@pulumi/pulumi": "^3.86.0",
    "@pulumi/auth0": "^2.24.3"
  }
```

### Example

```
const myRolePerms = auth0.RolePermissions("myRolePerms", {
    roleId: myroleId,
    permissions: [
      {
        resourceServerIdentifier: myBackendApiIdentifier,
        name: "create:user"
      }
    ],
  });
```

The permissions are not added to the role.

The roles are then also removed from the resource server **and the state file is not updated to describe this.**

To work around this, I have needed to use the syntax marked as deprecated to create permissions directly as an array attribute within roles.

### Output of `pulumi about`

Version      3.86.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME    VERSION
auth0   2.24.3
nodejs  unknown

Host     
OS       fedora
Version  38
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hi @1tmb, similarly to the other issue - could you try 3.0.0 and see if the issue still reproduces?

**Comment by 1tmb** [comment]
@mikhailshilkov all working well in v3.0.0, thank you!
