### ISSUE TITLE
Client Secret Unavailable In v3.0.0

### ISSUE THREAD

**Issue by source-studio** [pulumi/pulumi-auth0#314]
### What happened?

The `ClientSecret` property appears to have been removed from the `Client` resource in v3.0.0 of the provider, and it is not at all clear from the [migration guide](https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md#reading-client-secret) as to where this has been moved to or indeed how to retrieve it. Any guidance on this would be appreciated.

### Example

N/A

### Output of `pulumi about`

N/A

**Comment by source-studio** [comment]
Apologies, I didn't spot the the new `ClientCredentials` resource, which appears to be the mechanism by which secrets should be [managed and rotated](https://registry.terraform.io/providers/auth0/auth0/latest/docs/guides/client_secret_rotation#process-to-rotate-the-credentials) going forward.

**Comment by worldspawn** [comment]
>Public applications cannot use the client_credentials grant type. To use this grant type, you must configure the application to be confidential rather than public.

So for a "SPA"/"Native" what are we supposed to do??

**Comment by roblframpton** [comment]
Thanks @ricardoroyc for the function which fetches the secret.  Just in case anyone else has this issue, I found I had to change the return signiture or the types didn't match.  Here's the function I used:

```
function getClientSecret(client: auth0.Client): pulumi.Output<string> {
  return client.clientId.apply(async (id) => {
    const clientData = await auth0.getClient({ clientId: id });
    return clientData.clientSecret;
  });
}
```
