### ISSUE TITLE
Clarify tenant creation in doc

### ISSUE THREAD

**Issue by ericrudder** [pulumi/pulumi-auth0#34]
(Suggestion from Tomas Jansson)
Can I suggest that you update the description of the tenant provider, since now it is incorrect and could potentially ruin a real environment for someone if used without this knowledge.

[Tenant allows for setting properties, however doesn't actually create; see blog post for slightly more detail.]

**Comment by iwahbe** [comment]
The `auth0.Tenant` description states that the API does not support creating tenants.

![Image](https://github.com/user-attachments/assets/af48fd24-dae5-4221-9d04-feb2e25a39d1)


I think that docs generation fixes have gotten us where we want, but if not please open a new issue that explains the desired result.
