### ISSUE TITLE
Unable to remove "urlLifetimeInSeconds" from email template once set

### ISSUE THREAD

**Issue by ArcticGizmo** [pulumi/pulumi-auth0#412]
### What happened?

Removing the `urlLifetimeInSeconds` parameter from an existing `auth0.EmailTemplate` that was previously set to a value does not remove the parameter from the entity. This results in pulumi requesting that the parameter be removed but no state change actually occurs

### Create an email template with urlLifetimeInSeconds set
```
const emailProvider = new auth0.EmailProvider(
    'Sendgrid-EmailProvider',
    {
        credentials: {
            apiKey: '{my-api-key}',
        },
        defaultFromAddress: 'no-reply@somedomain.com',
        enabled: true,
        name: 'sendgrid',
    },
    { protect: false }
);

const welcomeEmailEmailTemplate = new auth0.EmailTemplate(
    'WelcomeEmail-EmailTemplate',
    {
        template: 'welcome_email',
        body: '{my-html-body}',
        from: 'no-reply@somedomain.com',
        subject: 'Welcome',
        syntax: 'liquid',
        urlLifetimeInSeconds: 432000,
        enabled: true,
    },
    { dependsOn: [emailProvider] }
);
```

### remove urlLifetimeInSeconds
```
const welcomeEmailEmailTemplate = new auth0.EmailTemplate(
    'WelcomeEmail-EmailTemplate',
    {
        template: 'welcome_email',
        body: '{my-html-body}',
        from: 'no-reply@somedomain.com',
        subject: 'Welcome',
        syntax: 'liquid',
        enabled: true,
    },
    { dependsOn: [emailProvider] }
);
```

### Output of `pulumi about`

CLI
Version      3.103.1
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME    VERSION
auth0   3.1.0
nodejs  unknown

Host
OS       Microsoft Windows 10 Pro
Version  10.0.19045 Build 19045
Arch     x86_64

This project is written in nodejs: executable='C:\programs\nodejs\node.exe' version='v20.4.0'

### Additional context

I have manually tried to fix the entities via the management API using https://auth0.com/docs/api/management/v2/email-templates/put-email-templates-by-template-name but the PUT semantics of the endpoint are not being enforced when optional keys are not present in the body. I have raised this with Auth0 support and they have confirmed the endpoint is not behaving as expected, but there is no ETA on when this will be resolved on their end (ticket: #02335958)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @ArcticGizmo. Thanks for opening an issue here and tracking down the issue with Auth0. I'm not 100% sure what Pulumi can do to mitigate here. I can think of two workarounds:

Does setting `urlLifetimeInSeconds` to `0` resolve the problem, or does it actually set `urlLifetimeInSeconds` to `0`? If `urlLifetimeInSeconds` needs an explicit "empty" value passed, maybe 0 will do the trick. My guess is it depends on which language their backend was written in, but it's worth a shot.

You can set the `replaceOnChanges` resource option to `urlLifetimeInSeconds`. This will cause Pulumi to trigger a replace. This should work around this issue, but the resource will replace instead of update.

I hope that helped. Please let me know if either of these solutions work for you.

**Comment by ArcticGizmo** [comment]
@iwahbe thanks for the reply.

I have tried using `0` and `null` (despite null not being supported in the docs) but it just sets the key to that value without removing it.

I will investigate `replaceOnChanges` as it might just work for our use case, even if it is not ideal. Otherwise I will fall back to setting the `urlLifetimeInSeconds` on each template, even if it is functionally pointless.

I will mark this issue as closed as it is not really a pulumi issue at all, but at least anyone else who faces this issue should get an idea on how to proceed.

**Comment by iwahbe** [comment]
@ArcticGizmo Thanks for opening such a clear issue and leaving this breadcrumb for other users! If you have any ideas on how Pulumi can mitigate, don't hesitate to let us know.
