### ISSUE TITLE
TestAccClient failing

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-auth0#502]
### What happened?

```    auth0:index:Client (test):
      error: 1 error occurred:
      	* failed to send the request: Post "https://***/api/v2/clients": oauth2: "server_error" "callback is not a function"
      	
```

Also TestAccResourceServer

This is blocking https://github.com/pulumi/pulumi-auth0/actions/runs/8710853966/job/23893786532?pr=500 and https://github.com/pulumi/pulumi-auth0/pull/500

I'd suggest skipping the test if there is no quick resolution. Thank you.

### Example

See above.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Yeah, that's an issue from last week: https://github.com/pulumi/pulumi-auth0/issues/488

Unfortunately this is all of our tests in the provider - something's wrong with the credentials or account. I don't think we can really release it without any tests.

I'll add a skip for the tests to unblock work here but we should not release the provider before fixing the tests.

cc @guineveresaenger @iwahbe
