### ISSUE TITLE
Typescript Client Metadata type not consistent with terraform

### ISSUE THREAD

**Issue by austinrivas** [pulumi/pulumi-auth0#58]
The type defined for for the `Client.clientMetadata` custom resource property is incorrect.

```typescript
    /**
     * Map(String)
     */
    readonly clientMetadata: pulumi.Output<{
        [key: string]: any;
    } | undefined>;
```

When attempting to set client metadata to something like

```typescript
{
  clientMetada: {
    hasura: hasura.jwtClaimsNamespace,
  }
}
```

You get the following error

```
error: auth0:index/client:Client resource 'auth0-account-linking-client' has a problem: client_metadata (claimsNamespaces): '' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[hasura:https://hasura.io/jwt/claims]'
```

It seems as though the terraform provider is expecting a string map whereas the pulumi provider is an any map.

**Comment by mikhailshilkov** [comment]
I failed to reproduce this issue with a modern provider version. I set

```
    clientMetadata: {
        foo: "zoo",
    },
```

as in our API docs and did not receive a validation error.

I'll go ahead and close the issue. If anyone still experiences this problem, please report back.
