### ISSUE TITLE
microsoft azure active directory creation Error

### ISSUE THREAD

**Issue by ib-yasn** [pulumi/pulumi-auth0#76]
I have created a Microsoft azure AD connection using the Connection resource with the waad strategy. When I run pulumi up I get the following Error:
400 Bad Request: undefined is not a valid Windows Azure AD domain

## Expected behavior
Create an Azure AD connection on Auth0

## Current behavior
Error is thrown while creating the connection.

## Steps to reproduce
Create a resource such as:

```
const microsoftConnection = new auth0.Connection('microsoft-ad-connection', {
      strategy: 'waad',
      displayName: 'Microsoft AD',
      enabledClients: [websiteClient.clientId],
      name: 'microsoft-ad',
      options: {
        appId: authenticationConfig.require('microsoftAuthClientId'),
        clientId: authenticationConfig.require('microsoftAuthClientId'),
        clientSecret: authenticationConfig.requireSecret('microsoftAuthSecret'),
        domain: 'mydomain.com',
        waadCommonEndpoint: true,
        debug: true
      },
    });
```
It happens with fixed strings as well as config items.

## Context (Environment)
`pulumi version: v2.20.0`
`@pulumi/auth0: "^1.8.0"`

**Comment by lblackstone** [comment]
Have you tried setting the [`isDomainConnection`](https://www.pulumi.com/docs/reference/pkg/auth0/connection/#isdomainconnection_nodejs) option?

**Comment by lblackstone** [comment]
Marking as bug since the error message isn't useful.

**Comment by ib-yasn** [comment]
Thanks for the reply, from Auth0 perspective isDomainConnection is controlling 3rd party applications for that connection https://auth0.com/docs/applications/enable-third-party-applications. it is a different input for auth0.

can I debug json request sent to Auth0 ?

**Comment by lblackstone** [comment]
You should be able to see details about the request using verbose logs. See https://www.pulumi.com/docs/troubleshooting/#verbose-logging for details on enabling this.

**Comment by mjeffryes** [comment]
Unfortunately, it looks like this issue hasn't seen any updates in a while. If you're still encountering this problem, could you leave a quick comment to let us know so we can prioritize it? (Commenting will bump it back into our triage queue.)
