### ISSUE TITLE
Auth0 role is deleted but fails pulumi program

### ISSUE THREAD

**Issue by vubogovich** [pulumi/pulumi-auth0#81]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When auth0 role is deleted from the Pulumi program, `pulumi up` delete the corresponding auth0 resource but fails with the error:
```
  auth0:index:Role ({resource-name}):
    error: deleting urn:pulumi:***::***::auth0:index/role:Role::{resource-name}: json: Unmarshal(nil)
 
  pulumi:pulumi:Stack ({stack-name}):
    error: update failed
```

`@pulumi/auth0` version: 2.2.0
`@pulumi/pulumi` version: 3.4.0

### Steps to reproduce

1. Add a role definition to a pulumi program: `new auth0.Role(name, { name, description, permissions })`
2. Run `pulumi up` - successful and the role is created
3. Delete the role from the pulumi program
4. Run `pulumi up` - failed (see error above) and the role is deleted
5. Run `pulumi up` again - success

Expected: `pulumi up` is successful after the role is deleted from pulumi program

Actual: once the role is deleted from pulumi program, the first `pulumi up` is failing and the second one succeeds

**Comment by AaronFriel** [comment]
@vubogovich A lot has changed in Pulumi since this issue was opened, please let us know if this is an active issue for you on more recent releases, and if so open a new issue.
